version: 2
    
jobs:
  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install sphinx
          
      - run:
          name: Sphinx run
          command: make html
          
      - persist_to_workspace:
          root: build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "weigl@ci-build"
            git config user.name "Circle CI Build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist build/html
    
workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy
