site_name: Verification for Automated Production Systems
site_url: https://formal.iti.kit.edu/
#weigl/verifaps/
repo_url: https://github.com/example/repository/
site_description:
site_author: Alexander Weigl <weigl@kit.edu>

pages:
  - VerifAPS     : index.md
  - geteta       : geteta/index.md
  - stvs         : stvs/index.md
  - library      : library/index.md
  - demo         : demofinal/demo_final_workshop.md

theme_dir: kit_theme

markdown_extensions:
  - smarty
  - toc:
      permalink: True
      separator: "_"
  - sane_lists
