version: 2
    
jobs:
  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install sphinx
          
      - run:
          name: Sphinx run
          command: make html
          
      - persist_to_workspace:
          root: build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: build
      - add_ssh_keys:
          fingerprints:
            - "e9:e0:f1:7d:92:a1:83:a8:0b:3a:7b:ec:33:3d:29:f7"            
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "weigl@ci-build"
            git config user.name "Circle CI Build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist build/html
    
workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
